export type Photo = {
  id: string;
  src: string;
  title: string;
  place?: string;
  tag: "fashion" | "architecture" | "workout";
};

/** Fashion frames — Imagine set (local LoRA plates are off Vercel) */
export const photos: Photo[] = [
  // New expansion (Imagine set)
  {
    id: "gen-01",
    src: "/images/gen-01-emerald-wrap.jpg",
    title: "Emerald Wrap",
    place: "Full front · midday tropical",
    tag: "fashion",
  },
  {
    id: "gen-02",
    src: "/images/gen-02-cream-blazer.jpg",
    title: "Cream Blazer Walk",
    place: "3/4 · soft overcast",
    tag: "fashion",
  },
  {
    id: "gen-03",
    src: "/images/gen-03-turtleneck-profile.jpg",
    title: "Turtleneck Profile",
    place: "True side · golden hour",
    tag: "fashion",
  },
  {
    id: "gen-04",
    src: "/images/gen-04-red-overshoulder.jpg",
    title: "Red Over-Shoulder",
    place: "Back 3/4 · sunset",
    tag: "fashion",
  },
  {
    id: "gen-05",
    src: "/images/gen-05-slip-denim.jpg",
    title: "Slip & Denim",
    place: "Low hero · hard noon",
    tag: "fashion",
  },
  {
    id: "gen-06",
    src: "/images/gen-06-cobalt-seated.jpg",
    title: "Cobalt Seated",
    place: "3/4 sit · open shade",
    tag: "fashion",
  },
  {
    id: "gen-07",
    src: "/images/gen-07-beauty-beige.jpg",
    title: "Beauty Beige",
    place: "Close front · soft fill",
    tag: "fashion",
  },
  {
    id: "gen-08",
    src: "/images/gen-08-blazer-bluehour.jpg",
    title: "Blue Hour Laugh",
    place: "Close 3/4 · rim light",
    tag: "fashion",
  },
  {
    id: "gen-09",
    src: "/images/gen-09-navy-jumpsuit.jpg",
    title: "Navy Jumpsuit",
    place: "Full front · soft afternoon",
    tag: "fashion",
  },
  {
    id: "gen-10",
    src: "/images/gen-10-plum-night.jpg",
    title: "Plum Night",
    place: "Back turn · string lights",
    tag: "fashion",
  },
  {
    id: "gen-11",
    src: "/images/gen-11-grey-studio.jpg",
    title: "Grey Studio",
    place: "Full front · softbox",
    tag: "fashion",
  },
  {
    id: "gen-12",
    src: "/images/gen-12-coral-coord.jpg",
    title: "Coral Co-ord",
    place: "Dynamic 3/4 · golden rim",
    tag: "fashion",
  },
  {
    id: "gen-13",
    src: "/images/gen-13-laugh.jpg",
    title: "Laugh",
    place: "Close front · tropical bokeh",
    tag: "fashion",
  },
  {
    id: "gen-14",
    src: "/images/gen-14-serene.jpg",
    title: "Serene",
    place: "Eyes closed · same knit",
    tag: "fashion",
  },
  {
    id: "gen-15",
    src: "/images/gen-15-34-look.jpg",
    title: "Three-quarter look",
    place: "3/4 · off-camera",
    tag: "fashion",
  },
  {
    id: "gen-16",
    src: "/images/gen-16-profile.jpg",
    title: "Profile",
    place: "Left profile · tropical",
    tag: "fashion",
  },
  {
    id: "gen-17",
    src: "/images/gen-17-saree.jpg",
    title: "Maroon Saree",
    place: "Golden-hour garden",
    tag: "fashion",
  },
  {
    id: "gen-18",
    src: "/images/gen-18-lehenga.jpg",
    title: "Ivory Lehenga",
    place: "Marble hall · crop choli",
    tag: "fashion",
  },
  {
    id: "gen-19",
    src: "/images/gen-19-sequin.jpg",
    title: "Black Sequin",
    place: "Terrace night · party",
    tag: "fashion",
  },
  {
    id: "gen-20",
    src: "/images/gen-20-backless.jpg",
    title: "Champagne Satin",
    place: "Party light · low neck",
    tag: "fashion",
  },
  {
    id: "gen-21",
    src: "/images/gen-21-slit-saree.jpg",
    title: "Emerald Slit Saree",
    place: "Evening hall",
    tag: "fashion",
  },
  {
    id: "gen-22",
    src: "/images/gen-22-sharara.jpg",
    title: "Mint Sharara",
    place: "Courtyard · crop blouse",
    tag: "fashion",
  },
  {
    id: "gen-23",
    src: "/images/gen-23-red-lehenga.jpg",
    title: "Red Mirror Lehenga",
    place: "Banquet · party",
    tag: "fashion",
  },
  {
    id: "gen-24",
    src: "/images/gen-24-silver.jpg",
    title: "Silver Bodycon",
    place: "Club rim light",
    tag: "fashion",
  },
  {
    id: "gen-25",
    src: "/images/gen-25-serious.jpg",
    title: "Serious",
    place: "Close · no smile",
    tag: "fashion",
  },
  {
    id: "gen-26",
    src: "/images/gen-26-look-up.jpg",
    title: "Look up",
    place: "Chin up · tropical",
    tag: "fashion",
  },
  {
    id: "gen-27",
    src: "/images/gen-27-look-down.jpg",
    title: "Look down",
    place: "Eyes down · tropical",
    tag: "fashion",
  },
  {
    id: "gen-28",
    src: "/images/gen-28-34-right.jpg",
    title: "Three-quarter right",
    place: "Face 3/4 · other side",
    tag: "fashion",
  },
  {
    id: "gen-29",
    src: "/images/gen-29-profile-right.jpg",
    title: "Right profile",
    place: "True profile",
    tag: "fashion",
  },
  {
    id: "gen-30",
    src: "/images/gen-30-over-shoulder.jpg",
    title: "Over-shoulder face",
    place: "Look back · beauty",
    tag: "fashion",
  },
  {
    id: "gen-31",
    src: "/images/gen-31-noon-squint.jpg",
    title: "Noon sun",
    place: "Hard light · close",
    tag: "fashion",
  },
  {
    id: "gen-32",
    src: "/images/gen-32-blue-hour.jpg",
    title: "Blue hour",
    place: "Rim light · close",
    tag: "fashion",
  },
  {
    id: "gen-33",
    src: "/images/gen-33-walk.jpg",
    title: "Walk",
    place: "Garden path · overcast",
    tag: "fashion",
  },
  {
    id: "gen-34",
    src: "/images/gen-34-sit-steps.jpg",
    title: "Sit steps",
    place: "Open shade",
    tag: "fashion",
  },
  {
    id: "gen-35",
    src: "/images/gen-35-window-lean.jpg",
    title: "Window lean",
    place: "Side light",
    tag: "fashion",
  },
  {
    id: "gen-36",
    src: "/images/gen-36-hands-hair.jpg",
    title: "Hands in hair",
    place: "Grey studio",
    tag: "fashion",
  },
  {
    id: "gen-37",
    src: "/images/gen-37-lookback-coat.jpg",
    title: "Lookback coat",
    place: "Blue hour",
    tag: "fashion",
  },
  {
    id: "gen-38",
    src: "/images/gen-38-noon-stand.jpg",
    title: "Noon stand",
    place: "Hard sun · grey cami",
    tag: "fashion",
  },
  {
    id: "gen-39",
    src: "/images/gen-39-tungsten-sit.jpg",
    title: "Tungsten sit",
    place: "Indoor lamps",
    tag: "fashion",
  },
  {
    id: "gen-40",
    src: "/images/gen-40-overcast.jpg",
    title: "Overcast",
    place: "Wet daylight · jumpsuit",
    tag: "fashion",
  },

  // Original Grok Imagine set
  {
    id: "3cf63eb8",
    src: "/images/3cf63eb8-3338-46e3-9d8b-2d08d775ed4c.jpg",
    title: "Yellow Floral Sundress",
    place: "Tree-lined park · full front",
    tag: "fashion",
  },
  {
    id: "142c2511",
    src: "/images/142c2511-9d2c-4469-a540-524ff39d818c.jpg",
    title: "Linen & Laugh",
    place: "White shirt · blue shorts",
    tag: "fashion",
  },
  {
    id: "de4e3f32",
    src: "/images/de4e3f32-a973-4dad-b1d7-1a6efe06141e.jpg",
    title: "Coral Maxi",
    place: "Side profile · golden hour",
    tag: "fashion",
  },
  {
    id: "fdcb4672",
    src: "/images/fdcb4672-faef-4448-bbf3-d366dfd03679.jpg",
    title: "Olive Slip",
    place: "Seated · garden bench",
    tag: "fashion",
  },
  {
    id: "6b204030",
    src: "/images/6b204030-f231-4855-b1aa-f25a077957a0.jpg",
    title: "Soft Close-Up",
    place: "Beige cashmere · beauty",
    tag: "fashion",
  },
];

/** Reproducible face/body architecture boards */
export const architecture: Photo[] = [
  {
    id: "arch-face",
    src: "/images/architecture/arch-face-orthographic.jpg",
    title: "Face Multi-Angle",
    place: "Front · 3/4 L · 3/4 R · profile",
    tag: "architecture",
  },
  {
    id: "arch-body",
    src: "/images/architecture/arch-body-turnaround.jpg",
    title: "Body Turnaround",
    place: "Front · 3/4 · side · back",
    tag: "architecture",
  },
  {
    id: "arch-expr",
    src: "/images/architecture/arch-expression-sheet.jpg",
    title: "Expression Sheet",
    place: "Neutral · smile · laugh · serene",
    tag: "architecture",
  },
  {
    id: "arch-light",
    src: "/images/architecture/arch-lighting-study.jpg",
    title: "Lighting Study",
    place: "Golden · overcast · noon · blue hour",
    tag: "architecture",
  },
];

/** Identity-locked workout / fitness set (modest athletic wear) */
export const workout: Photo[] = [
  {
    id: "wo-02",
    src: "/images/workout/wo-02-gym-squat.jpg",
    title: "Gym Squat",
    place: "Dumbbells · long-sleeve set",
    tag: "workout",
  },
  {
    id: "wo-03",
    src: "/images/workout/wo-03-outdoor-run.jpg",
    title: "Park Run",
    place: "Mid-stride · coral top",
    tag: "workout",
  },
  {
    id: "wo-04",
    src: "/images/workout/wo-04-yoga-warrior.jpg",
    title: "Yoga Warrior",
    place: "Studio · sage set",
    tag: "workout",
  },
  {
    id: "wo-05",
    src: "/images/workout/wo-05-boxing.jpg",
    title: "Boxing Guard",
    place: "Gym · navy training",
    tag: "workout",
  },
  {
    id: "wo-06",
    src: "/images/workout/wo-06-cable-row.jpg",
    title: "Cable Row",
    place: "Strength · seated pull",
    tag: "workout",
  },
  {
    id: "wo-07",
    src: "/images/workout/wo-07-stretch-hoodie.jpg",
    title: "Cool-down Stretch",
    place: "Hoodie · calf stretch",
    tag: "workout",
  },
  {
    id: "wo-08",
    src: "/images/workout/wo-08-post-workout.jpg",
    title: "Post-workout",
    place: "Close · towel · soft smile",
    tag: "workout",
  },
  {
    id: "wo-09",
    src: "/images/workout/wo-09-cycling.jpg",
    title: "Cycling",
    place: "Outdoor · road bike",
    tag: "workout",
  },
  {
    id: "wo-10",
    src: "/images/workout/wo-10-squat-stand.jpg",
    title: "Squat stand",
    place: "Top of the rep · dumbbells",
    tag: "workout",
  },
  {
    id: "wo-11",
    src: "/images/workout/wo-11-squat-deep.jpg",
    title: "Squat depth",
    place: "Thighs parallel · dumbbells",
    tag: "workout",
  },
  {
    id: "wo-12",
    src: "/images/workout/wo-12-boxing-jab.jpg",
    title: "Boxing jab",
    place: "Right hand · same gym",
    tag: "workout",
  },
  {
    id: "wo-13",
    src: "/images/workout/wo-13-boxing-hook.jpg",
    title: "Boxing hook",
    place: "Weight shift · same gym",
    tag: "workout",
  },
  {
    id: "wo-14",
    src: "/images/workout/wo-14-row-pull.jpg",
    title: "Row pull",
    place: "Handles to ribs",
    tag: "workout",
  },
  {
    id: "wo-15",
    src: "/images/workout/wo-15-row-extend.jpg",
    title: "Row extend",
    place: "Start of the pull",
    tag: "workout",
  },
];

/** Same yellow sundress, same public-park path — original stand plus five pose edits */
export const sundress: Photo[] = [
  {
    id: "garden-hero",
    src: "/images/3cf63eb8-3338-46e3-9d8b-2d08d775ed4c.jpg",
    title: "Front stand",
    place: "Yellow floral · tree-lined park",
    tag: "fashion",
  },
  {
    id: "gen-41",
    src: "/images/gen-41-yellow-34.jpg",
    title: "Three-quarter",
    place: "Same dress · park path",
    tag: "fashion",
  },
  {
    id: "gen-42",
    src: "/images/gen-42-yellow-sit.jpg",
    title: "Garden sit",
    place: "Stone bench · same park",
    tag: "fashion",
  },
  {
    id: "gen-43",
    src: "/images/gen-43-yellow-hip.jpg",
    title: "Hand on hip",
    place: "Same dress · park path",
    tag: "fashion",
  },
  {
    id: "gen-44",
    src: "/images/gen-44-yellow-walk.jpg",
    title: "Walk",
    place: "Mid-stride · skirt in motion",
    tag: "fashion",
  },
  {
    id: "gen-45",
    src: "/images/gen-45-yellow-lookback.jpg",
    title: "Look back",
    place: "Over-shoulder · same park",
    tag: "fashion",
  },
];

export const fashionPhotos = photos.filter((p) => p.tag === "fashion");
export const workoutPhotos = workout;
export const sundressPhotos = sundress;
